# Put SELinux in permissive mode, logging actions that would be blocked.
- name: change selinux settings to permissive mode
  become: true
  selinux:
    policy: targeted
    state: permissive

- name: install java 1.8 openjdk 
  become: true
  yum:
    name: java-1.8.0-openjdk
    state: present


- name: add elasticsearch public GPG key
  become: true
  rpm_key:
    state: present
    key: http://packages.elastic.co/GPG-KEY-elasticsearch


- name: Add yum repository for kibana
  become: true
  yum_repository:
    name: kibana-6.4
    description: Kibana repository for 6.4.x packages
    file: kibana
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: yes
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes


- name: install the latest version of kibana
  become: true
  yum:
    name: kibana
    state: latest


- name: Add yum repository for nginx
  become: true
  yum_repository:
    name: nginx-repo
    description: Nginx repository for nginx packages
    file: nginx
    baseurl: http://nginx.org/packages/mainline/rhel/7/$basearch/
    gpgcheck: no
    enabled: yes



- name: install  NGINX
  become: true
  yum:
    name: nginx
    state: latest


- name: copying kibana config from template
  become: true
  template: src=kibana.yml dest=/etc/kibana/kibana.yml owner=root group=root mode=0664


- name: copying nginx config from template
  become: true
  template: src=nginx.conf dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=655

- name: Restart service kibana, in all cases
  become: true
  service:
    name: kibana
    state: restarted
    enabled: yes

- name: Restart service nginx, in all cases
  become: true
  service:
    name: nginx
    state: restarted
    enabled: yes


- name: Start service nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: open service in firewall
  become: true
  firewalld:
    service: kibana
    permanent: true
    state: enabled
    zone: public
    immediate: true

- name: open nginx 80 port in firewall
  become: true
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true
