- name: install java rpm from a local file
  become: true
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: add elasticsearch public GPG key
  become: true
  rpm_key:
    state: present
    key: http://packages.elastic.co/GPG-KEY-elasticsearch


- name: Add yum repository for elasticsearch
  become: true
  yum_repository:
    name: elasticsearch-2.x
    description: Elasticsearch repository for 2.x packages
    file: elasticsearch
    baseurl: http://packages.elastic.co/elasticsearch/2.x/centos
    gpgcheck: yes
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes


- name: install the latest version of elasticsearch
  become: true
  yum:
    name: elasticsearch
    state: latest

- name: copying elasticsearch.yml config from template
  become: true
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml owner=root group=elasticsearch mode=0760



- name: Restart service elasticsearch, in all cases
  become: true
  service:
    name: elasticsearch
    state: restarted
    enabled: yes


- name: open elasticsearch service in firewall
  become: true
  firewalld:
    service: elasticsearch
    permanent: true
    state: enabled
    zone: public
    immediate: true
