- name: copying rpm files
  copy:
    src: rpms
    dest: /tmp/
    owner: admina
    group: admina
    mode: 0644

- name: install java rpm from a local file
  become: true
  yum:
    name: /tmp/rpms/jdk-8u181-linux-x64.rpm
    state: present


- name: add elasticsearch public GPG key
  become: true
  rpm_key:
    state: present
    key: http://packages.elastic.co/GPG-KEY-elasticsearch


- name: Add yum repository for logstash
  become: true
  yum_repository:
    name: logstash-2.2
    description: logstash repository for 2.2 packages
    file: logstash
    baseurl: http://packages.elasticsearch.org/logstash/2.2/centos
    gpgcheck: yes
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes


- name: install the latest version of logstash
  become: true
  yum:
    name: logstash
    state: latest


- name: copying logstash 02-beats-input.conf config from template
  become: true
  template: src=logstash/02-beats-input.conf dest=/etc/logstash/conf.d/02-beats-input.conf owner=root group=root mode=0664


- name: copying logstash 10-syslog-filter.conf config from template
  become: true
  template: src=logstash/10-syslog-filter.conf dest=/etc/logstash/conf.d/10-syslog-filter.conf owner=root group=root mode=0664


- name: copying logstash 30-elasticsearch-output.conf config from template
  become: true
  template: src=logstash/30-elasticsearch-output.conf dest=/etc/logstash/conf.d/30-elasticsearch-output.conf owner=root group=root mode=0664


- name: Restart service logstash, in all cases
  become: true
  service:
    name: logstash
    state: restarted
    enabled: yes


- name: open logstash service in firewall
  become: true
  firewalld:
    port: 5044/tcp
    permanent: true
    state: enabled
    zone: public
    immediate: true

